# Site settings
title: ISWC2016
email: your-email@domain.com
description: ISWC 2016 is the premier international forum, for the Semantic Web / Linked Data Community. Here, scientists, industry specialists, and practitioners meet to discuss the future of practical, scalable, user-friendly, and game changing solutions. Come and join us 17-21 October 2016 in Kobe to hear!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://iswc2016.semanticweb.org/" # the base hostname & protocol for your site
twitter_username: iswc2016
github_username:  iswc2016

# Build settings
markdown: kramdown
#highlighter: rouge

#Github URL
github_ghpages: "https://github.com/iswc2016/iswc2016/blob/gh-pages"

voting: false
voting_url: "https://iswc.lodac.nii.ac.jp/iswc-vote/vote.php"
paper_links: true
paper_url: "https://iswc.lodac.nii.ac.jp/files"
offline: true
