# Site settings
title: ISWC2016
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/iswc2016" # the subpath of your site, e.g. /blog/
url: "http://iswc2016.semanticweb.org/" # the base hostname & protocol for your site
twitter_username: iswc2016
github_username:  iswc2016

# Build settings
markdown: kramdown
#highlighter: rouge
